create table if not exists tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  is_processed boolean not null default false,
  importance integer,
  urgency integer,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists journals (
  id bigint generated by default as identity primary key,
  content text not null,
  tags text[] not null default '{}',
  mood_score integer,
  created_at timestamptz not null default now()
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  amount numeric,
  category text,
  expense_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists monthly_settings (
  month_key text primary key,
  income numeric not null default 0,
  fixed_cost numeric not null default 0,
  savings_target numeric not null default 0
);

alter table tasks disable row level security;
alter table journals disable row level security;
alter table expenses disable row level security;
alter table monthly_settings disable row level security;
